# Generated by Django 3.0.1 on 2020-01-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charblog', models.CharField(blank=True, max_length=50000, null=True)),
                ('fileblog', models.FileField(blank=True, null=True, upload_to='problem1/media')),
                ('fileblog_content', models.CharField(blank=True, max_length=50000, null=True)),
                ('fileblog_updated_content', models.CharField(blank=True, max_length=50000, null=True)),
                ('charblog_updated_content', models.CharField(blank=True, max_length=50000, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updationTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
